import { datePipe } from "./datePipe";

export const defaultData = {
  id: 0,
  worker: "",
  company: "",
  sales: "",
  contractRange: `${datePipe(new Date())}~${datePipe(new Date())}`,
  paidFrom: 140,
  paidTo: 180,
  contractType: "準委任契約",
  subject: "",
  document: "作業報告書",
  isHour: false,
  periodDate: "",
  workPrice: 500000,
  roundDigit: 1,
  roundType: "round",
  calcType: "highLow",
  overPrice: 2800,
  underPrice: 3600,
  workerId: 0,
  salesId: 0,
  companyId: 0,
  isFixed: false,
};
