// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/claim/create": {
    params: {};
  };
  "/claim/data": {
    params: {};
  };
  "/contract/data": {
    params: {};
  };
  "/contract/detail/new": {
    params: {};
  };
  "/contract/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/data": {
    params: {};
  };
  "/order/create": {
    params: {};
  };
  "/order/data": {
    params: {};
  };
  "/quote/create": {
    params: {};
  };
  "/quote/data": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/claim/create" | "/claim/data" | "/contract/data" | "/contract/detail/new" | "/contract/detail/:id" | "/data" | "/order/create" | "/order/data" | "/quote/create" | "/quote/data";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/claim.create/index.tsx": {
    id: "routes/claim.create/index";
    page: "/claim/create";
  };
  "routes/claim.data/index.tsx": {
    id: "routes/claim.data/index";
    page: "/claim/data";
  };
  "routes/contract.data/index.tsx": {
    id: "routes/contract.data/index";
    page: "/contract/data";
  };
  "routes/contract.detail.new/index.tsx": {
    id: "routes/contract.detail.new/index";
    page: "/contract/detail/new";
  };
  "routes/contract.detail.$id/index.tsx": {
    id: "routes/contract.detail.$id/index";
    page: "/contract/detail/:id";
  };
  "routes/data/index.tsx": {
    id: "routes/data/index";
    page: "/data";
  };
  "routes/order.create/index.tsx": {
    id: "routes/order.create/index";
    page: "/order/create";
  };
  "routes/order.data/index.tsx": {
    id: "routes/order.data/index";
    page: "/order/data";
  };
  "routes/quote.create/index.tsx": {
    id: "routes/quote.create/index";
    page: "/quote/create";
  };
  "routes/quote.data/index.tsx": {
    id: "routes/quote.data/index";
    page: "/quote/data";
  };
};